defaults: &defaults
  docker:
    - image: circleci/openjdk:10-jdk-node

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Image
          command: |
            docker build -t rigosolutions/mvn-chrome .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
