defaults: &defaults
  docker:
    - image: circleci/openjdk:10-jdk-node

  working_directory: ~/docker-mvn-chrome

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Image
          command: |
            docker build -t rigosolutions/mvn-chrome .
            docker tag rigosolutions/mvn-chrome:latest rigosolutions/mvn-chrome:${CIRCLE_SHA1}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push rigosolutions/mvn-chrome:latest
            docker logout

  release:
    <<: *defaults

    steps:
      - attach_workspace:
            at: ~/docker-mvn-chrome
      - setup_remote_docker
      - run:
          name: Build and Release Image
          command: |
            docker build -t rigosolutions/mvn-chrome .
            docker tag rigosolutions/mvn-chrome:latest rigosolutions/mvn-chrome:${CIRCLE_TAG}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push
            docker logout

workflows:
  version: 2

  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop

#  build-and-release:
#    jobs:
#      - build:
#         filters:
#           branches:
#             only:
#               - master
#      - release:
#          tags:
#            only: /^v.*/
